# Generated by Django 3.2 on 2022-04-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_rename_prine_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
