# Generated by Django 3.2 on 2022-04-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_rename_quantity_orderitem_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shippingAddress',
        ),
    ]
