# Generated by Django 3.2 on 2022-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/blueprint.jpg', null=True, upload_to=''),
        ),
    ]
